錒ppliname: app
version: 1.0.0

server:
  port: 8080


# 对应 MybatisProperties
mybatis:
        typeAliasesPackage: com.kyx.app.bean
        mapperLocations: classpath*:mapper/*Mapper.xml


# the current active profile : dev
spring:
  profiles.active: dev

# Multi-profile
# if the profile is dev ,the datasource is as following:
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true #default is true

# 根据具体使用的第三方数据源设置
# 不缩进@ConfigurationProperties(prefix = "dataSource")
# 缩进：@ConfigurationProperties(prefix = "spring.dataSource")
  dataSource:
    #data-source-class-name: com.zaxxer.hikari.pplicaHikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/material?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    poolName: springHikariCP
    autoCommit: false
    minimumIdle: 20
    maximumPoolSize: 20
    connectionInitSql: SELECT 1
    dataSourceProperty:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true



logging:
  level:
    com.kyx.app: DEBUG

---

# if profiles is test , the datasource does't need  to be configured
spring:
  profiles: test


logging:
  level:
    com.kyx.app: ERROR








