name: app
version: 1.0.0

server:
  port: 8081

# the current active profile : dev
spring:
  profiles.active: dev

# Multi-profile
# if the profile is dev ,the datasource is as following:
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true #default is true


dataSource:
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/material?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456
  poolName: springHikariCP
  autoCommit: false
  minimumIdle: 20
  maximumPoolSize: 20
  connectionInitSql: SELECT 1
  dataSourceProperty:
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true

mybatis:
    type-aliases-package: com.kyx.app.bean
    mapper-locations: classpath*:mapper/*Mapper.xml
    #mapper-locations: classpath*:*Mapper.xml


---

# if profiles is test , the datasource does't need  to be configured
spring:
  profiles: test


flyway:
  enabled: ${flyware-enabled:false}

logging:
  level:
    com.kyx.app: DEBUG




